// <auto-generated />
namespace PAC_Web.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class datetime_datatypemigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(datetime_datatypemigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202410020715596_datetime_datatypemigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
